//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakingWaves.Helsetilsynet.Intranet.Web.Templates.Pages {
    
    
    public partial class LargeDocumentChapter {
        
        /// <summary>
        /// LeftMenu2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MakingWaves.Helsetilsynet.Intranet.Web.Templates.Units.Placeable.LeftMenuLargeDocuments LeftMenu2;
    }
}
