//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakingWaves.Helsetilsynet.Intranet.Web.Templates.Pages {
    
    
    public partial class StartPage {
        
        /// <summary>
        /// featured control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MakingWaves.Helsetilsynet.Intranet.Web.Templates.Units.Placeable.FeaturedArticles featured;
        
        /// <summary>
        /// activityFeed control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MakingWaves.Helsetilsynet.Intranet.Web.Templates.Units.Static.ActivityFeed activityFeed;
        
        /// <summary>
        /// rssFrontPage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MakingWaves.Helsetilsynet.Intranet.Web.Templates.Units.Placeable.RSS rssFrontPage;
        
        /// <summary>
        /// CalendarFullVersion1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MakingWaves.Helsetilsynet.Intranet.Web.Templates.Units.Placeable.CalendarFullVersion CalendarFullVersion1;
    }
}
