//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakingWaves.Helsetilsynet.Intranet.Web.Templates.Units.Login {
    
    
    public partial class Login {
        
        /// <summary>
        /// litInfoText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litInfoText;
        
        /// <summary>
        /// livLogin control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LoginView livLogin;
        
        /// <summary>
        /// ucRegister control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MakingWaves.Helsetilsynet.Intranet.Web.Templates.Units.Login.Register ucRegister;
        
        /// <summary>
        /// ucForgotPassword control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MakingWaves.Helsetilsynet.Intranet.Web.Templates.Units.Login.ForgotPassword ucForgotPassword;
        
        /// <summary>
        /// ucNewPassword control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MakingWaves.Helsetilsynet.Intranet.Web.Templates.Units.Login.NewPassword ucNewPassword;
        
        /// <summary>
        /// litInfoText2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litInfoText2;
    }
}
