//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helsetilsynet.templates.Avenir.Webparts {
    
    
    public partial class ManagementConsole {
        
        /// <summary>
        /// WebPartManagementConsole1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EPiCode.WebParts.EPiChrome.WebPartManagementConsole WebPartManagementConsole1;
        
        /// <summary>
        /// ThemeCatalogZone control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.WebParts.CatalogZone ThemeCatalogZone;
        
        /// <summary>
        /// ThemeDeclarativeCatalog control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.WebParts.DeclarativeCatalogPart ThemeDeclarativeCatalog;
    }
}
