//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helsetilsynet.templates.Avenir.Pages {
    
    
    public partial class LargeDocument {
        
        /// <summary>
        /// LeftMenuLargeDocuments control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Helsetilsynet.templates.Avenir.Units.Placeable.LargeDocuments.LeftMenuLargeDocuments LeftMenuLargeDocuments;
        
        /// <summary>
        /// GeneratePdf control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Helsetilsynet.templates.Avinir.Units.Placeable.LargeDocuments.Units.Placeable.GeneratePDF GeneratePdf;
        
        /// <summary>
        /// phDocumentTableOfContents control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder phDocumentTableOfContents;
        
        /// <summary>
        /// MenuOnRootChapter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Helsetilsynet.templates.Avenir.Units.Placeable.LargeDocuments.MenuOnRootChapter MenuOnRootChapter;
        
        /// <summary>
        /// phContentOfBelowDocs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder phContentOfBelowDocs;
        
        /// <summary>
        /// rptBelowDocs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptBelowDocs;
    }
}
