//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avenir.Templates.Pages {
    
    
    public partial class Lover {
        
        /// <summary>
        /// ChangedPages control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Avenir.Templates.Units.Placeable.ChangedPages ChangedPages;
        
        /// <summary>
        /// KeywordList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Avenir.Templates.Units.Placeable.KeywordList KeywordList;
    }
}
