	

	

	<script language="JavaScript">	

	

	

	function initPbox() {

		var objSelectDT = document.all[selectPid];	
		var avaluesDT = valuePstring.split(',');			
		for (var t=0; t<avaluesDT.length; t++) {

			for(var i=0; i < objSelectDT.length; i++)

			{

				if (avaluesDT[t] == objSelectDT[i].value && objSelectDT[i].value.length>0) 
				{
					objSelectDT[i].selected = true; 
				}

			}	
		}

	}

	

	function GetPValue()

	{

		var strSaveDT = "";

		var objSelectDT = document.all[selectPid];

		var objTextDT = document.all[hiddenPid];

		

		for(var i=0; i < objSelectDT.length; i++)

		{

			if(objSelectDT[i].selected)

			{

				if(strSaveDT == "")

				{

					strSaveDT += objSelectDT[i].value;

				}

				else

				{

					strSaveDT += "," + objSelectDT[i].value;

				}

				

			}

		}

		

		objTextDT.value = strSaveDT;

	}

	

	initPbox();

	

	</script>

	