	

	

	<script language="JavaScript">	

	

	

	function initRbox() {

		var objSelectDT = document.all[selectRid];	
		var avaluesDT = valueRstring.split(',');			
		for (var t=0; t<avaluesDT.length; t++) {

			for(var i=0; i < objSelectDT.length; i++)

			{

				if (avaluesDT[t] == objSelectDT[i].value && objSelectDT[i].value.length>0) 
				{
					objSelectDT[i].selected = true; 
				}

			}	
		}

	}

	

	function GetRValue()

	{

		var strSaveDT = "";

		var objSelectDT = document.all[selectRid];

		var objTextDT = document.all[hiddenRid];

		

		for(var i=0; i < objSelectDT.length; i++)

		{

			if(objSelectDT[i].selected)

			{

				if(strSaveDT == "")

				{

					strSaveDT += objSelectDT[i].value;

				}

				else

				{

					strSaveDT += "," + objSelectDT[i].value;

				}

				

			}

		}

		

		objTextDT.value = strSaveDT;

	}

	

	initRbox();

	

	</script>

	